In [4]:
%matplotlib inline


PyTorch가 무엇인가요?
=======================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

- NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

시작하기
-----------

Tensors
^^^^^^^

Tensor는 NumPy의 ndarray와 유사하며, GPU를 사용한 연산 가속도 가능합니다.



In [5]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을
    포함하고 있지는 않습니다. 초기화되지 않은 행렬이 생성되면 그 시점에 할당된
    메모리에 존재하던 값들이 초기값으로 나타납니다.</p></div>



초기화되지 않은 5x3 행렬을 생성합니다:



In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])


무작위로 초기화된 행렬을 생성합니다:



In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3731, 0.8703, 0.9819],
        [0.3976, 0.4846, 0.2096],
        [0.0164, 0.9100, 0.7708],
        [0.3178, 0.1092, 0.8051],
        [0.8787, 0.0549, 0.3788]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성합니다:



In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 기존 tensor를 바탕으로 새로운 tensor를 만듭니다. 이들 메소드(method)는
사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(예. dtype)을
재사용합니다.



In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9780,  0.7768, -1.2005],
        [ 2.5276,  0.1509, -0.1578],
        [-0.3366, -0.5235,  0.1687],
        [ 1.0738,  0.1953, -2.5635],
        [ 0.6524, -1.3813, -0.3376]])


행렬의 크기를 구합니다:



In [11]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 는 튜플(tuple) 타입으로, 모든 튜플 연산을 지원합니다.</p></div>

연산(Operations)
^^^^^^^^^^^^^^^^
연산을 위한 여러가지 문법을 제공합니다. 다음 예제들을 통해 덧셈 연산을 살펴보겠습니다.

덧셈: 문법1



In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.9046,  1.5316, -1.1332],
        [ 2.7001,  0.4859, -0.1384],
        [ 0.3123, -0.1692,  0.8208],
        [ 1.2362,  0.9854, -2.2679],
        [ 1.0537, -1.0764,  0.5403]])


덧셈: 문법2



In [13]:
print(torch.add(x, y))

tensor([[ 2.9046,  1.5316, -1.1332],
        [ 2.7001,  0.4859, -0.1384],
        [ 0.3123, -0.1692,  0.8208],
        [ 1.2362,  0.9854, -2.2679],
        [ 1.0537, -1.0764,  0.5403]])


덧셈: 결과 tensor를 인자로 제공



In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.9046,  1.5316, -1.1332],
        [ 2.7001,  0.4859, -0.1384],
        [ 0.3123, -0.1692,  0.8208],
        [ 1.2362,  0.9854, -2.2679],
        [ 1.0537, -1.0764,  0.5403]])


덧셈: 바꿔치기(in-place) 방식



In [15]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 2.9046,  1.5316, -1.1332],
        [ 2.7001,  0.4859, -0.1384],
        [ 0.3123, -0.1692,  0.8208],
        [ 1.2362,  0.9854, -2.2679],
        [ 1.0537, -1.0764,  0.5403]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(in-place) 방식으로 tensor의 값을 변경하는 연산 뒤에는 ``_``가 붙습니다.
    예: ``x.copy_(y)``, ``x.t_()`` 는 ``x`` 를 변경합니다.</p></div>

NumPy스러운 인덱싱 표기 방법을 사용하실 수도 있습니다!



In [16]:
print(x[:, 1])

tensor([ 0.7768,  0.1509, -0.5235,  0.1953, -1.3813])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 ``torch.view`` 를 사용합니다:



In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원에서 유추합니다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면, ``.item()`` 을 사용하면 숫자 값을 얻을 수 있습니다.



In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3810])
-1.3809568881988525


**더 읽을거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산,
  선형 대수, 난수(random number) 등, 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>`_ 에서 확인하실 수 있습니다.

NumPy 변환(Bridge)
-------------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을
공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

Torch Tensor를 NumPy 배열로 변환하기
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy 배열을 Torch Tensor로 변환하기
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
np (NumPy) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로 변환할 수 있고,
(NumPy에서 Tensor로의) 반대 변환도 가능합니다.

CUDA Tensors
------------

``.to`` 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [23]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

C:\Users\melon\anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
